# Generated by Django 6.0.5 on 2026-05-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_city_student_email_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.CharField(default='Absent', max_length=20),
        ),
    ]
